public class ContentCacheWrapper {
	public String contentId;
	public String authorId;
	public String authorName;
	public String siteId;
    public String imgUrl;
    public String imgLandscapeUrl;
	public String siteImgContentDocumentId;
    public Boolean isPromoted;
    public String categoryName;
    public String categoryId;
	public String contentDocumentId;
    public String type;
	public String title;
    public String excerpt;
	public Boolean isMustRead;
    public String publishAt;
	public String publishTo;
	public String startsAt;
	public String endsAt;
	public String timezoneIso;
	public String timezoneName;
	public Integer timezoneOffset;
    public String createdAt;
	public String modifiedAt;
	public String promoteAt;
	public String promoteTo;
	public Boolean isAllDay;
	public Boolean isMultiDay;
	public Boolean hasRead;
	public Boolean hasSeen;
	public Boolean isFavorited;
	public Boolean isDeleted;
	public Boolean isActivatedByFeature;
	public Boolean isShowInSimpplrEnabled;
	public String status;
	public ContentCacheWrapper(){
        
    }
}