public with sharing class OembedModel {
	public String type;				
	public String version;
	public String title;			
    public String author_name;		
    public String author_url;		
    public String provider_name;
    public String provider_url;
    public String cache_age;
    public String thumbnail_url;
    public String thumbnail_width;
    public String thumbnail_height;	
    public String description;		
    public String url;				
    public String html;			
    public Integer width;			
    public Integer height;			
}